@startuml
title Lieferkette-Risiko-Radar - Aktivitaetsdiagramm
start
:Nutzer oeffnet Spielseite (_ghtml_lieferkette_risiko_radar.html);
:Konfigurationsdaten laden (_data/_gg01_lieferkette_risiko_radar.json);
while (Runden offen?) is (ja)
  :Prompt anzeigen;
  :Antwort auswaehlen;
  if (Antwort korrekt?) then (ja)
    :Punkte erhoehen;
  else (nein)
    :Fehlerfeedback zeigen;
  endif
endwhile (nein)
:Ergebnis anzeigen;
stop
@enduml
