@startuml
title Komponenten-/Package-Diagramm: Auftragsdurchlauf-Timer
left to right direction
skinparam packageStyle rectangle

package "Ordner: auftragsdurchlauf_timer" {
  component "_ghtml_auftragsdurchlauf_timer.html" as HTML
  component "_gjs_auftragsdurchlauf_timer.js" as JS
  component "_gcss_auftragsdurchlauf_timer.css" as CSS
  database "_data/_gg01_auftragsdurchlauf_timer.json" as GG
  database "_data/__metaData_Aufbau, grundlegende Arbeits- und Geschaeftsprozesse im Betrieb.json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
