@startuml
title Komponenten-/Package-Diagramm: Kuendigungsgrund-Klassifikator
left to right direction
skinparam packageStyle rectangle

package "Ordner: kuendigungsgrund_klassifikator" {
  component "_ghtml_kuendigungsgrund_klassifikator.html" as HTML
  component "_gjs_kuendigungsgrund_klassifikator.js" as JS
  component "_gcss_kuendigungsgrund_klassifikator.css" as CSS
  database "_data/_gg01_kuendigungsgrund_klassifikator.json" as GG
  database "_data/__metaData_Kündigung - Kündigungsschutz (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
