@startuml
title Komponenten-/Package-Diagramm: Akteurszuordnung-Match
left to right direction
skinparam packageStyle rectangle

package "Ordner: akteurszuordnung_match" {
  component "_ghtml_akteurszuordnung_match.html" as HTML
  component "_gjs_akteurszuordnung_match.js" as JS
  component "_gcss_akteurszuordnung_match.css" as CSS
  database "_data/_gg01_akteurszuordnung_match.json" as GG
  database "_data/__metaData_Beteiligte im dualen System (Betrieb, Berufsschule, zustaendige Stelle, ggf. UEBS).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
