@startuml
title Komponenten-/Package-Diagramm: Ordnungsprinzip-Match
left to right direction
skinparam packageStyle rectangle

package "Ordner: ordnungsprinzip_match" {
  component "_ghtml_ordnungsprinzip_match.html" as HTML
  component "_gjs_ordnungsprinzip_match.js" as JS
  component "_gcss_ordnungsprinzip_match.css" as CSS
  database "_data/_gg01_ordnungsprinzip_match.json" as GG
  database "_data/__metaData_Soziale Marktwirtschaft als Grundprinzip (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
