@startuml
title Verlagerungsszenario-Simulator - Aktivitaetsdiagramm
start
:Nutzer oeffnet Spielseite (_ghtml_verlagerungsszenario_simulator.html);
:Konfig laden (_data/_gg01_verlagerungsszenario_simulator.json);
while (Runden offen?) is (ja)
  :Szenario lesen;
  :Option waehlen;
  if (Auswahl korrekt?) then (ja)
    :Punkte erhoehen;
  else (nein)
    :Feedback + Abzug;
  endif
endwhile (nein)
:Ergebnis anzeigen;
stop
@enduml
