@startuml
left to right direction
actor Player
rectangle "kreditvertrag" {
  usecase "Entscheidung treffen" as UC1
  usecase "Feedback erhalten" as UC2
  usecase "Fortschritt messen" as UC3
}
Player --> UC1
Player --> UC2
Player --> UC3
@enduml
