@startuml
title Komponenten-/Package-Diagramm: Organigramm-Sorter
left to right direction
skinparam packageStyle rectangle

package "Ordner: organigramm_sorter" {
  component "_ghtml_organigramm_sorter.html" as HTML
  component "_gjs_organigramm_sorter.js" as JS
  component "_gcss_organigramm_sorter.css" as CSS
  database "_data/_gg01_organigramm_sorter.json" as GG
  database "_data/__metaData_Ziele, Aufgaben, Aufbau von Unternehmen - Organisationen (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
