@startuml
title Komponenten-/Package-Diagramm: Werbe-Filter
left to right direction
skinparam packageStyle rectangle

package "Ordner: werbe_filter" {
  component "_ghtml_werbe_filter.html" as HTML
  component "_gjs_werbe_filter.js" as JS
  component "_gcss_werbe_filter.css" as CSS
  database "_data/_gg01_werbe_filter.json" as GG
  database "_data/__metaData_Bedürfnisse, Bedarf, Kaufkraft (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
