@startuml
title Komponenten-/Package-Diagramm: Lieferketten-Router
left to right direction
skinparam packageStyle rectangle

package "Ordner: lieferketten_router" {
  component "_ghtml_lieferketten_router.html" as HTML
  component "_gjs_lieferketten_router.js" as JS
  component "_gcss_lieferketten_router.css" as CSS
  database "_data/_gg01_lieferketten_router.json" as GG
  database "_data/__metaData_Chancen - Risiken Europa & Globalisierung (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
