@startuml
title Komponenten-/Package-Diagramm: Verlagerungsszenario-Simulator
left to right direction
skinparam packageStyle rectangle

package "Ordner: verlagerungsszenario_simulator" {
  component "_ghtml_verlagerungsszenario_simulator.html" as HTML
  component "_gjs_verlagerungsszenario_simulator.js" as JS
  component "_gcss_verlagerungsszenario_simulator.css" as CSS
  database "_data/_gg01_verlagerungsszenario_simulator.json" as GG
  database "_data/__metaData_Standortwettbewerb (z. B. Lohnniveau, Nachhaltigkeitsstandards – Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
