@startuml
title Komponenten-/Package-Diagramm: Plan-Abgleich-Matrix
left to right direction
skinparam packageStyle rectangle

package "Ordner: plan_abgleich_matrix" {
  component "_ghtml_plan_abgleich_matrix.html" as HTML
  component "_gjs_plan_abgleich_matrix.js" as JS
  component "_gcss_plan_abgleich_matrix.css" as CSS
  database "_data/_gg01_plan_abgleich_matrix.json" as GG
  database "_data/__metaData_Ausbildungsordnung, Ausbildungsrahmenplan, betrieblicher Ausbildungsplan (Bezuege herstellen).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
