@startuml
title Komponenten-/Package-Diagramm: Widerruf-Timer
left to right direction
skinparam packageStyle rectangle

package "Ordner: widerruf_timer" {
  component "_ghtml_widerruf_timer.html" as HTML
  component "_gjs_widerruf_timer.js" as JS
  component "_gcss_widerruf_timer.css" as CSS
  database "_data/_gg01_widerruf_timer.json" as GG
  database "_data/__metaData_Verbraucherschutz (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
