@startuml
title Komponenten-/Package-Diagramm: Schichtplan-Rechner
left to right direction
skinparam packageStyle rectangle

package "Ordner: schichtplan_rechner" {
  component "_ghtml_schichtplan_rechner.html" as HTML
  component "_gjs_schichtplan_rechner.js" as JS
  component "_gcss_schichtplan_rechner.css" as CSS
  database "_data/_gg01_schichtplan_rechner.json" as GG
  database "_data/__metaData_Arbeitszeit, Urlaub, Entgeltfortzahlung.json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
