@startuml
title Komponenten-/Package-Diagramm: Entgeltfortzahlung-Timer
left to right direction
skinparam packageStyle rectangle

package "Ordner: entgeltfortzahlung_timer" {
  component "_ghtml_entgeltfortzahlung_timer.html" as HTML
  component "_gjs_entgeltfortzahlung_timer.js" as JS
  component "_gcss_entgeltfortzahlung_timer.css" as CSS
  database "_data/_gg01_entgeltfortzahlung_timer.json" as GG
  database "_data/__metaData_Arbeitszeit, Urlaub, Entgeltfortzahlung.json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
