@startuml
title Prozessfluss-Timeline - Aktivitaetsdiagramm
start
:Nutzer oeffnet Spielseite (_ghtml_prozessfluss_timeline.html);
:Konfig laden (_data/_gg01_prozessfluss_timeline.json);
while (Runden offen?) is (ja)
  :Prompt lesen;
  :Option waehlen;
  if (korrekt?) then (ja)
    :Punkte gutschreiben;
  else (nein)
    :Feedback + Abzug;
  endif
endwhile (nein)
:Ergebnis anzeigen;
stop
@enduml
