@startuml
title Komponenten-/Package-Diagramm: Kostenfluss-Analyse
left to right direction
skinparam packageStyle rectangle

package "Ordner: kostenfluss_analyse" {
  component "_ghtml_kostenfluss_analyse.html" as HTML
  component "_gjs_kostenfluss_analyse.js" as JS
  component "_gcss_kostenfluss_analyse.css" as CSS
  database "_data/_gg01_kostenfluss_analyse.json" as GG
  database "_data/__metaData_Stellung des Betriebs in Branche - Wertschoepfung.json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
