@startuml
title Komponenten-/Package-Diagramm: Rechte-Radar
left to right direction
skinparam packageStyle rectangle

package "Ordner: rechte_radar" {
  component "_ghtml_rechte_radar.html" as HTML
  component "_gjs_rechte_radar.js" as JS
  component "_gcss_rechte_radar.css" as CSS
  database "_data/_gg01_rechte_radar.json" as GG
  database "_data/__metaData_Verbraucherschutz (Grundidee).json" as META
  folder "_assets" as ASSETS
  folder "__dokumentation" as DOC
}

HTML --> JS
HTML --> CSS
JS --> GG
JS --> META
HTML --> ASSETS
@enduml
